### ISSUE TITLE
Does it work on linux?

### ISSUE THREAD

**Issue by gleb-kun** [D7EAD/CoinGecko#6]
Can I use this library on Linux?

**Comment by gleb-kun** [comment]
If not, do you plan to add cross-platform in the future?

**Comment by D7EAD** [comment]
Hi.

While I haven't updated the library in a while, I would have no reason to believe it wouldn't compile and link under Linux, assuming the library's `DllExport` macro is updated to be placed in a platform-dependent `#ifdef.`

You can open a PR to do this if you'd like, or I will do it later.

**Comment by gleb-kun** [comment]
Thanks for the info!
